---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-own
  namespace: my-own
  labels:
    app: my-pod-own
spec:
  containers:
    - name: my-container-own
      image: yuvanatagore/my-portfolio:latest
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-own
  namespace: my-own
spec:
  type: LoadBalancer
  selector:
    app: my-pod-own
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
